### ISSUE TITLE
Datasets to run the experiments

### ISSUE THREAD

**Issue by Kaushalya** [rmgarnett/active_learning#4]
Thanks for sharing the code. I'm trying to reproduce the paper "Efficient nonmyopic active search". Is the Citeseer dataset available for downloading?
Can you share a link to the original dataset used in the experiments?

**Comment by shalijiang** [comment]
Hi Kaushalya,

Thanks for your interet in our work. I just published the code and some datasets here: https://github.com/shalijiang/efficient_nonmyopic_active_search.git
Let me know if you have any questions. 

Shali

**Comment by Kaushalya** [comment]
Thank you very much. I'm closing the issue.
